FROM php:5.6.1-apache
COPY webpage.html /var/www/html/webpage.html
COPY inventory.php /var/www/html/inventory.php
RUN chmod 600 /var/www/html/webpage.html
RUN chmod 600 /var/www/html/inventory.php
EXPOSE 80